# 03 numpy.array 基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.13.3'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.13.3'

## 1) Python List的特点

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [7]:
L[5] = "MengYuan"
L

[0, 1, 2, 3, 4, 'MengYuan', 6, 7, 8, 9]

In [8]:
import array

In [9]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5] = "MengYuan"
arr

TypeError: an integer is required (got type str)

## 2) numpy.array

In [11]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
nparr[5]

5

In [14]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [15]:
nparr[5] = "MengYuan"
nparr

ValueError: invalid literal for int() with base 10: 'MengYuan'

In [16]:
nparr.dtype

dtype('int32')

In [17]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
nparr.dtype

dtype('int32')

In [19]:
nparr[5] = 3.14
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [20]:
nparr.dtype

dtype('int32')

In [23]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([ 1.,  2.,  3.])

In [24]:
nparr2.dtype

dtype('float64')

## 3) 其他创建 numpy.array的方法

In [25]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
np.zeros(10).dtype

dtype('float64')

In [27]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.zeros((3, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [29]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [31]:
np.ones((3, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [34]:
np.full(shape=(3, 5), fill_value=666.0)

array([[ 666.,  666.,  666.,  666.,  666.],
       [ 666.,  666.,  666.,  666.,  666.],
       [ 666.,  666.,  666.,  666.,  666.]])

In [35]:
np.full(fill_value=666.0, shape=(3, 5))

array([[ 666.,  666.,  666.,  666.,  666.],
       [ 666.,  666.,  666.,  666.,  666.],
       [ 666.,  666.,  666.,  666.,  666.]])

## 3) arange

In [36]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [37]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
[i for i in range(0, 1, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [39]:
np.arange(0, 2, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8])

In [40]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 4) linspace (x, y, z）对于终止点是包含的，指的是在指定范围[x,y]内截取z个数并且等差)

In [42]:
np.linspace(0, 20, 10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [43]:
np.linspace(0, 20, 11)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

## 5) random

In [44]:
np.random.randint(0, 10) # 随机一个整数，范围0到10，前闭后开

6

In [46]:
np.random.randint(0, 10, 10) # 前闭后开，第三个参数是size

array([9, 7, 6, 4, 3, 7, 6, 9, 5, 2])

In [47]:
np.random.randint(4, 8, size=10) # 第三个大小的关键字形式

array([4, 6, 4, 4, 7, 4, 4, 6, 5, 7])

In [48]:
np.random.randint(4, 8, size=(3, 5)) # 大小指定为3行5列矩阵表示

array([[5, 6, 7, 7, 4],
       [6, 4, 7, 5, 6],
       [5, 6, 4, 6, 5]])

In [61]:
np.random.seed(666) # 种子一样随机数一样
np.random.randint(4.0, 8.0, size=(3, 5)) # 前闭后开

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [50]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5)) 

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [63]:
np.random.random(10) # 随机数

array([ 0.28116849,  0.46284169,  0.23340091,  0.76706421,  0.81995656,
        0.39747625,  0.31644109,  0.15551206,  0.73460987,  0.73159555])

In [65]:
np.random.random(10) # 10个随机数

array([ 0.8578588 ,  0.76741234,  0.95323137,  0.29097383,  0.84778197,
        0.3497619 ,  0.92389692,  0.29489453,  0.52438061,  0.94253896])

In [54]:
np.random.random((3, 5)) # 三行五列随机数，大小在0到1之间

array([[ 0.76741234,  0.95323137,  0.29097383,  0.84778197,  0.3497619 ],
       [ 0.92389692,  0.29489453,  0.52438061,  0.94253896,  0.07473949],
       [ 0.27646251,  0.4675855 ,  0.31581532,  0.39016259,  0.26832981]])

In [55]:
np.random.normal(10, 100) # 均值，标准差（所有数减去其平均值的平方和，所得结果除以该组数之个数（或个数减一，即变异数），再把所得值开根号，所得之数就是这组数据的标准差）

87.60516793129695

In [56]:
np.random.normal(0, 1, (3, 5)) # 均值，标准差, size

array([[ 1.18063598,  0.06102404,  1.07856138, -0.79783572,  1.1701326 ],
       [ 0.1121217 ,  0.03185388, -0.19206285,  0.78611284, -1.69046314],
       [-0.98873907,  0.31398563,  0.39638567,  0.57656584, -0.07019407]])

In [58]:
np.random.normal?

In [59]:
np.random?

In [60]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap