## 1) 合并操作

In [3]:
import numpy as np

In [9]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [11]:
x

array([1, 2, 3])

In [12]:
y

array([3, 2, 1])

In [13]:
np.concatenate([x, y]) # 拼接两个array

array([1, 2, 3, 3, 2, 1])

In [14]:
z = np.array([666, 666, 666])

In [15]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [16]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [17]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [18]:
np.concatenate([A, A], axis=1) # axis指定按维度拼接

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [19]:
np.concatenate([A, z]) # 维度不一样无法用concatenate拼接

ValueError: all the input arrays must have same number of dimensions

In [20]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [21]:
A #concatenate新创建了副本

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.vstack([A, z]) # vstack 在垂直方向堆叠

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [23]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [24]:
np.hstack([A, B]) # hstack 在水平方向堆叠

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 2) 分割

In [25]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x1, x2, x3 = np.split(x, [3, 7])
x1

array([0, 1, 2])

In [27]:
x2

array([3, 4, 5, 6])

In [28]:
x3

array([7, 8, 9])

In [29]:
x1, x2 = np.split(x, [5])

In [30]:
x1

array([0, 1, 2, 3, 4])

In [31]:
x2

array([5, 6, 7, 8, 9])

In [35]:
x = np.arange(5, -1, -1)
x

array([5, 4, 3, 2, 1, 0])

In [36]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
A1, A2 = np.split(A, [2])

In [38]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
A1, A2 = np.split(A, [2], axis=1)
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [41]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [42]:
upper, lower = np.vsplit(A, [2])

In [43]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
upper, lower = np.hsplit(A, [2])

In [46]:
upper

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [47]:
lower

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [48]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
X, y = np.hsplit(data, [-1]) # 模拟一个类似特征和期望的数据模型分割

In [50]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [51]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [53]:
y[:, 0]

array([ 3,  7, 11, 15])